# Generated by Django 5.1.4 on 2024-12-21 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('num_of_lines_m', models.IntegerField(default=0)),
                ('num_of_columns_n', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('line', models.IntegerField(default=0)),
                ('column', models.IntegerField(default=0)),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.matriz')),
            ],
        ),
    ]
