# Generated by Django 5.1.4 on 2024-12-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='line',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='element',
            name='value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='num_of_columns_n',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='matriz',
            name='num_of_lines_m',
            field=models.IntegerField(),
        ),
    ]
